# Generated by Django 5.1.6 on 2025-02-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='withdrawal_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('btc', 'Bitcoin'), ('tether', 'Tether'), ('binance', 'Binance')], default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
