# Generated by Django 5.1.6 on 2025-02-22 09:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RenameField(
            model_name='income',
            old_name='date_received',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to='tasks.userprofile'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('btc', 'Bitcoin'), ('tether', 'Tether'), ('binance', 'Binance')], default='mpesa', max_length=20),
        ),
    ]
