# Generated by Django 5.1.6 on 2025-02-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_withdrawalrequest_withdrawal_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tasks_completed_today',
            field=models.BooleanField(default=False),
        ),
    ]
