# Generated by Django 5.1.6 on 2025-02-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_userprofile_tasks_completed_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tasks_completed_today',
            field=models.IntegerField(default=0),
        ),
    ]
