# Generated by Django 5.1.6 on 2025-02-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_plan_earnings_per_task_plan_earnings_per_mine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='earnings_per_mine',
        ),
        migrations.AddField(
            model_name='plan',
            name='daily_ads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='daily_mines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='invitation_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='membership_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='reward_per_ad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='reward_per_mine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_activation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
