# Generated by Django 5.1.6 on 2025-02-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_userprofile_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'verbose_name_plural': 'Withdrawals'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'verbose_name_plural': 'Withdrawal Requests'},
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='tasks.userprofile'),
        ),
    ]
