# Generated by Django 5.1.6 on 2025-02-28 22:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_userprofile_tasks_completed_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningsrecord',
            name='total_referral_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
