# Generated by Django 5.1.6 on 2025-03-03 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_earningsrecord_total_referral_earnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earningsrecord',
            name='total_referral_earnings',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='tasks.userprofile'),
        ),
    ]
