# Generated by Django 5.1.6 on 2025-02-24 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_income_amount_alter_income_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='tasks.userprofile'),
        ),
    ]
