# Generated by Django 5.1.6 on 2025-02-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_userprofile_total_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='timestamp',
        ),
    ]
