# Generated by Django 5.1.6 on 2025-03-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_earningsrecord_total_referral_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
