# Generated by Django 5.1.6 on 2025-02-24 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_income_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
