# Generated by Django 5.1.6 on 2025-03-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_userprofile_referral_restricted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='daily_income',
            new_name='todays_income',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_referrals',
            field=models.IntegerField(default=0),
        ),
    ]
