# Generated by Django 5.1.6 on 2025-03-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_daily_income_userprofile_todays_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='todays_income',
            new_name='daily_income',
        ),
    ]
