# Generated by Django 5.1.6 on 2025-03-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_rename_todays_income_userprofile_daily_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='total_referrals',
        ),
    ]
