# Generated by Django 5.1.6 on 2025-02-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_rename_created_at_task_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_count',
            field=models.IntegerField(default=0),
        ),
    ]
