# Generated by Django 5.1.6 on 2025-02-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_method',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('BTC', 'Bitcoin'), ('Bank', 'Bank Transfer')], default='Mpesa', max_length=50),
        ),
    ]
