# Generated by Django 5.1.6 on 2025-03-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_userprofile_total_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='todays_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_referrals',
            field=models.IntegerField(default=0),
        ),
    ]
