# Generated by Django 5.1.6 on 2025-02-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_withdrawal_withdrawal_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('btc', 'BTC'), ('usdt', 'USDT'), ('binance', 'Binance')], default='mpesa', max_length=20),
        ),
    ]
