# Generated by Django 5.1.6 on 2025-03-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_userprofile_last_spin_result_userprofile_spin_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
