# Generated by Django 5.1.6 on 2025-03-07 23:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_userprofile_referral_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
